<%
   String clientIP = request.getRemoteAddr();
   System.out.println(clientIP);
%>
<html>
<head>
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
 <title>livegarbage Live Recording Reviews</title>
</head>

<body bgcolor=#8000FF>
<center>

<table width=75% border=1 bgcolor=#FFD6E6>
<tr bgcolor=#FFA9E7><td align=center><h1><a href="http://www.livegarbage.org">Live Garbage Hub</a></h1></td></tr>
<tr bgcolor=#FFC5E7><td align=center><h2>Live Recording List &amp; Fan Reviews</h2></td></tr>
</table>
<br><br><br>
